
// remote/src/App.js
import React from "react";

export const App = () => {
  return (
  <div>
    <h1>Imported from App "C"!!!</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta officiis, sunt error consequuntur suscipit magnam, assumenda consectetur debitis minus, repudiandae dolorem ipsa unde numquam inventore quia laborum laudantium maiores deleniti aliquid voluptatum. Odio, recusandae adipisci dignissimos repudiandae dicta soluta repellat illum perferendis itaque, nulla doloribus assumenda eaque nihil sapiente consectetur aliquam aperiam. Quis, voluptas architecto non deserunt molestias ab. Ipsum ducimus corporis enim voluptatibus quidem autem delectus. Delectus magni, ad distinctio in nulla quasi aperiam. Numquam, sit ducimus sed doloribus atque facilis obcaecati possimus est ipsam excepturi alias ratione corporis, quis aut! Delectus perferendis laudantium ullam asperiores molestias nihil inventore libero deleniti reiciendis quos, nobis vel vitae quis incidunt aut voluptates ipsum. Corrupti quod eum neque debitis at animi nisi expedita dolore officiis corporis error minus pariatur soluta alias, temporibus architecto recusandae asperiores quia iste sunt, voluptate nulla eligendi. Aut sapiente, commodi sequi magni ex dolores laudantium id voluptatibus repellat cumque suscipit dignissimos ipsam amet, doloremque error quo laborum optio! Itaque unde dicta sint ducimus eum nemo aut ipsum, fuga provident cum, rem voluptate asperiores, explicabo placeat eligendi tempora. Tenetur eaque repellat quisquam consequatur doloremque quibusdam placeat dolorum voluptatum vitae asperiores quaerat quis hic sed ipsum, ab, dolorem laborum dolores perspiciatis pariatur impedit magni fugiat, ullam minus earum! Repellendus eligendi ullam suscipit quo. Beatae iusto laboriosam quisquam! Error aperiam, quod asperiores ex repellendus, consectetur voluptatem vero deleniti necessitatibus tempore ea quas dicta nobis distinctio odio voluptate incidunt aliquid esse. Totam non error omnis veritatis architecto suscipit ratione unde. Consequatur quidem veniam dolorem nobis dicta tempore, dignissimos quos, non error deserunt iure eos voluptatibus hic eligendi doloribus obcaecati officiis aliquid excepturi quam minima rerum iusto necessitatibus? Sint assumenda ducimus accusantium dignissimos sapiente, amet exercitationem. Eius maxime vel consequatur corrupti at, natus expedita. Maiores obcaecati expedita quod doloribus sapiente in minus commodi!</p>
  </div>
  )
};
export default App;